import "./reset.css";
import "./global.css";

export const metadata = {
  title: "Word Game",
  description: "Word Game generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
